-- Sprawdź, czy tabela "recipes" jest pusta
DECLARE @rowCount INT;
SELECT @rowCount = COUNT(*) FROM recipes;

-- Jeśli tabela jest pusta (liczba wierszy wynosi 0), dodaj przepis
IF @rowCount = 0
BEGIN

    INSERT INTO ingredients (name)
VALUES
    ('Eggs'),
    ('Milk'),
    ('Flour'),
    ('Sugar'),
    ('Butter'),
    ('Salt'),
    ('Pepper'),
    ('Onion'),
    ('Garlic'),
    ('Tomatoes'),
    ('Chicken'),
    ('Beef'),
    ('Pork'),
    ('Fish'),
    ('Potatoes'),
    ('Carrots'),
    ('Celery'),
    ('Spinach'),
    ('Broccoli'),
    ('Bell Peppers'),
    ('Mushrooms'),
    ('Olive Oil'),
    ('Lemon Juice'),
    ('Basil'),
    ('Oregano'),
    ('Thyme'),
    ('Rosemary'),
    ('Cumin'),
    ('Coriander'),
    ('Chili Powder'),
    ('Paprika'),
    ('Cayenne Pepper'),
    ('Cinnamon'),
    ('Nutmeg'),
    ('Vanilla Extract'),
    ('Honey'),
    ('Soy Sauce'),
    ('Sesame Oil'),
    ('Vinegar'),
    ('Rice'),
    ('Pasta'),
    ('Bread'),
    ('Cheese'),
    ('Yogurt'),
    ('Cream'),
    ('Ketchup'),
    ('Mustard'),
    ('Mayonnaise'),
    ('Pickles'),
    ('Lettuce'),
    ('Cabbage'),
    ('Avocado'),
    ('Salsa'),
    ('Sour Cream'),
    ('Tofu'),
    ('Quinoa'),
    ('Brown Rice'),
    ('Black Beans'),
    ('Kidney Beans'),
    ('Lentils'),
    ('Chickpeas'),
    ('Walnuts'),
    ('Almonds'),
    ('Peanuts'),
    ('Cashews'),
    ('Sunflower Seeds'),
    ('Pine Nuts'),
    ('Cheddar Cheese'),
    ('Parmesan Cheese'),
    ('Feta Cheese'),
    ('Blue Cheese'),
    ('Swiss Cheese'),
    ('Provolone Cheese'),
    ('Gouda Cheese'),
    ('Brie Cheese'),
    ('Camembert Cheese'),
    ('Gruyère Cheese'),
    ('Cottage Cheese'),
    ('Cream Cheese'),
    ('Ricotta Cheese'),
    ('Mozzarella Cheese'),
    ('Cherry Tomatoes'),
    ('Zucchini'),
    ('Asparagus'),
    ('Pumpkin'),
    ('Strawberries'),
    ('Blueberries'),
    ('Raspberries'),
    ('Bananas'),
    ('Apples'),
    ('Oranges'),
    ('Grapes'),
    ('Watermelon'),
    ('Pineapple'),
    ('Coconut'),
    ('Mango'),
    ('Kiwi'),
    ('Peaches'),
    ('Plums'),
    ('Dates'),
    ('Prunes'),
    ('Raisins'),
    ('Apricots'),
    ('Cranberries'),
    ('Pomegranate'),
    ('Orange Juice'),
    ('Apple Juice'),
    ('Grape Juice'),
    ('Cranberry Juice'),
    ('Tomato Juice'),
    ('Carrot Juice'),
    ('Almond Milk'),
    ('Soy Milk'),
    ('Coconut Milk'),
    ('Cashew Milk'),
    ('Hemp Milk'),
    ('Rice Milk'),
    ('Oat Milk'),
    ('Quinoa Flour'),
    ('Almond Flour'),
    ('Coconut Flour'),
    ('Baking Powder'),
    ('Baking Soda'),
    ('Cornstarch'),
    ('Arrowroot Powder'),
    ('Agave Nectar'),
    ('Maple Syrup'),
    ('Molasses'),
    ('Balsamic Vinegar'),
    ('Red Wine Vinegar'),
    ('White Wine Vinegar'),
    ('Rice Vinegar'),
    ('Sesame Seeds'),
    ('Poppy Seeds'),
    ('Chia Seeds'),
    ('Flaxseeds'),
    ('Pumpkin Seeds'),
    ('Cumin Seeds'),
    ('Mustard Seeds'),
    ('Paprika Powder'),
    ('Curry Powder'),
    ('Turmeric Powder'),
    ('Garam Masala'),
    ('Cocoa Powder'),
    ('Chocolate Chips'),
    ('Dried Cranberries'),
    ('Raisins'),
    ('Granola'),
    ('Peanut Butter'),
    ('Nutella'),
    ('Marshmallows'),
    ('Graham Crackers'),
    ('Ice Cream'),
    ('Whipped Cream'),
    ('Caramel Sauce'),
    ('Hot Fudge'),
    ('Cherries'),
    ('Sprinkles'),
    ('Nuts and Bolts');
    -- Dodaj przepis do tabeli "recipes"
    INSERT INTO recipes (RecipeName, Description, preptime, servings)
    VALUES ('Scrambled Eggs', 'Rozbij jajka do miski, ubij je widelcem, dodaj sól i pieprz. Rozgrzej patelnię z masłem, wlej roztrzepane jajka, mieszaj na małym ogniu do uzyskania konsystencji jajecznicy.', 10, 2);

    -- Pobierz identyfikator dodanego przepisu
    DECLARE @recipeId INT;
    SET @recipeId = SCOPE_IDENTITY();

    -- Dodaj składniki do tabeli "ingredients" i utwórz relacje w tabeli "recipe_ingredients"
    

    -- Przypisz składniki do przepisu w tabeli "recipe_ingredients"
    INSERT INTO recipeingredients (recipeid, ingredientid) VALUES (@recipeId, 1); -- Przypisz jajka
    INSERT INTO recipeingredients (recipeid, ingredientid) VALUES (@recipeId, 5); -- Przypisz masło
    INSERT INTO recipeingredients (recipeid, ingredientid) VALUES (@recipeId, 6); -- Przypisz sól
    INSERT INTO recipeingredients (recipeid, ingredientid) VALUES (@recipeId, 7); -- Przypisz pieprz;

    INSERT INTO IngredientQuantities (RecipeId, ingredientid, Quantity, QuantityType) VALUES (@recipeId, 1, 2, 'pcs');
    INSERT INTO IngredientQuantities (RecipeId, ingredientid, Quantity, QuantityType) VALUES (@recipeId, 5, 2, 'teaspoon');
    INSERT INTO IngredientQuantities (RecipeId, ingredientid, Quantity, QuantityType) VALUES (@recipeId, 6, 1, 'pinch');
    INSERT INTO IngredientQuantities (RecipeId, ingredientid, Quantity, QuantityType) VALUES (@recipeId, 7, 1, 'pinch');
END
